### ISSUE TITLE
support @1x, @2x, @3x images?

### ISSUE THREAD

**Issue by vvenv** [crossjs/postcss-flexible#2]
before processing:

``` css
.selector {
  background-image: url(logo@2x.png);
}
```

after processing:

``` css
.selector {
}
[data-dpr="1"] .selector {
  background-image: url(logo@1x.png);
}
[data-dpr="2"] .selector {
  background-image: url(logo@2x.png);
}
[data-dpr="3"] .selector {
  background-image: url(logo@3x.png);
}
```
